version: '3.0'
services:

  irods:
    build:
      context: ./4.2.2
      dockerfile: Dockerfile
    image: mjstealey/irods-provider-cockroachdb:4.2.2
    container_name: irods
    environment:
      IRODS_HOST: irods
      IRODS_SERVICE_ACCOUNT_NAME: irods
      IRODS_SERVICE_ACCOUNT_GROUP: irods
      IRODS_SERVER_ROLE: 1
      ODBC_DRIVER_FOR_POSTGRES: 2
      IRODS_DATABASE_SERVER_HOSTNAME: database
      IRODS_DATABASE_SERVER_PORT: 5432
      IRODS_DATABASE_NAME: ICAT
      IRODS_DATABASE_USER_NAME: irods
      IRODS_DATABASE_PASSWORD: temppassword
      IRODS_DATABASE_USER_PASSWORD_SALT: tempsalt
      IRODS_ZONE_NAME: tempZone
      IRODS_PORT: 1247
      IRODS_PORT_RANGE_BEGIN: 20000
      IRODS_PORT_RANGE_END: 20199
      IRODS_CONTROL_PLANE_PORT: 1248
      IRODS_SCHEMA_VALIDATION: 'file:///var/lib/irods/configuration_schemas'
      IRODS_SERVER_ADMINISTRATOR_USER_NAME: rods
      IRODS_SERVER_ZONE_KEY: TEMPORARY_zone_key
      IRODS_SERVER_NEGOTIATION_KEY: TEMPORARY_32byte_negotiation_key
      IRODS_CONTROL_PLANE_KEY: TEMPORARY__32byte_ctrl_plane_key
      IRODS_SERVER_ADMINISTRATOR_PASSWORD: rods
      IRODS_VAULT_DIRECTORY: '/var/lib/irods/iRODS/Vault'
      UID_IRODS: 998
      GID_IRODS: 998
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    hostname: irods.local.dev
    networks:
      - irods
    # volumes:
    #   - ./var_irds:/var/lib/irods
    #   - ./etc_irods:/etc/irods

  database:
    image: postgres:10
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    hostname: database.local.dev
    networks:
      - irods

networks:
  irods:
